server:
  port: 7900
spring:
  application:
    name: provider-user
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false  #页面不加载缓存,自u该即时生效
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:  
  level:
    root: INFO
