server:
  port: 8761
spring:
  application:
    name: eurka-server
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false  #页面不加载缓存,自u该即时生效
eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/