server:
  port: 8050
  
spring:
  application:
    name: gateway-zuul
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false  #页面不加载缓存,自u该即时生效
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
      
zuul: 
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    app-provider-user:  
      path: /user/**
      serviceId: provider-user
    app-sidecar:  
      path: /sidecar/**
      serviceId:  sidecar
      
